site_name: AnyMusic

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - API Reference: reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
